kanban
  Todo
    [Create Documentation]
    docs[Create Blog about the new diagram]
  In Progress
    id6[Create renderer so that it works in all cases]
    id7[Write unit tests]
  Review
    id3[Code review for feature X]
  Done
    id5[Define getData]
    id2[Title of diagram]
