@startditaa
+--------+   +-------+    +-------+
|        +---+ ditaa |    |       |
|  Text  |   +-------+    |Diagram|
|Document|   |!magic!|    |       |
|     {d}+---+-------+--->+       |
+---+----+   |       |    |       |
    :        | ASCII |    +-------+
    |        +-------+
    v
+-----------+
| Beautiful |
|  Diagram  |
+-----------+
@endditaa
