mindmap
  root((Mind Map))
    Origins
      Long history
      Popularisation
        British psychological author Tony Buzan
    Research
      On effectiveness
      On automatic creation
        Uses
          Creative techniques
          Strategic planning
          Argument mapping
    Tools
      Pen and paper
      [Mermaid]
      ((Digital Apps))
    Benefits
      >Better recall]
      (Visual thinking)
      {Structured ideas}
