timeline
    title History of Social Media
    2002 : LinkedIn
    2004 : Facebook
         : Google
    2005 : YouTube
    2006 : Twitter
    2007 : Tumblr
    2010 : Instagram
    2011 : Snapchat
    2016 : TikTok
