timeline
    title Technology Milestones

    section Early Internet
        1990 : World Wide Web invented
        1993 : Mosaic browser released
        1995 : Amazon launches
             : eBay launches
             : JavaScript created

    section Search Era
        1998 : Google founded
        1999 : Napster launched
        2001 : Wikipedia launched
             : iTunes released

    section Social Media Era
        2004 : Facebook founded
        2005 : YouTube launched
        2006 : Twitter founded
        2007 : iPhone released
             : Android released

    section Mobile & Cloud
        2010 : Instagram launched
        2011 : Siri introduced
        2016 : TikTok launched
        2022 : ChatGPT released
