zenuml
    title Order Service
    @Actor Client #FFEBE6
    @Boundary OrderController
    @EC2 OrderService
    @Database Database #F5F5F5

    Client -> OrderController.createOrder(payload) {
        OrderController -> OrderService.create(payload) {
            OrderService -> Database.save(order) {
                return order
            }
            return order
        }
        return order
    }
