@startchronology
title Technology Timeline

[ARPANET First Message] happens on 1969-10-29
[Email Invented] happens on 1971-10-03
[TCP/IP Protocol] happens on 1983-01-01
[World Wide Web] happens on 1991-08-06
[Linux First Release] happens on 1991-09-17
[Google Founded] happens on 1998-09-04
[Wikipedia Launched] happens on 2001-01-15
[Facebook Founded] happens on 2004-02-04
[iPhone Released] happens on 2007-06-29
[GitHub Founded] happens on 2008-04-10
@endchronology
